package cn.cisdigital.datakits.framework.common.exception;

import cn.cisdigital.datakits.framework.model.interfaces.ErrorCode;
import cn.hutool.core.text.CharSequenceUtil;
import java.util.Arrays;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * @author xxx
 * @since 2024-05-08
 */
@Getter
@RequiredArgsConstructor
public enum DorisErrorCode implements ErrorCode {

    CREATE_TABLE_FAILED("1005", "doris.exception.create_table_failed"),
    DATABASE_ALREADY_EXISTS("1007", "doris.exception.database_already_exists"),
    DATABASE_NOT_EXIST("1008", "doris.exception.database_not_exist"),
    DATABASE_UNAUTHORIZED("1044", "doris.exception.database_unauthorized"),
    USERNAME_PASSWORD_NOT_MATCH("1045", "doris.exception.username_password_not_match"),
    NO_DATABASE_SELECTED("1046", "doris.exception.no_database_selected"),
    INVALID_COMMAND("1047", "doris.exception.invalid_command"),
    INVALID_DATABASE_SPECIFIED("1049", "doris.exception.invalid_database_specified"),
    TABLE_ALREADY_EXISTS("1050", "doris.exception.table_already_exists"),
    UNKNOWN_TABLE("1051", "doris.exception.unknown_table"),
    AMBIGUOUS_COLUMN_NAME("1052", "doris.exception.ambiguous_column_name"),
    INVALID_COLUMN_FOR_SEMIJOIN("1053", "doris.exception.invalid_column_for_semijoin"),
    COLUMN_NOT_FOUND("1054", "doris.exception.column_not_found"),
    COLUMN_COUNT_MISMATCH("1058", "doris.exception.column_count_mismatch"),
    DUPLICATE_COLUMN_NAME("1060", "doris.exception.duplicate_column_name"),
    NO_LIVING_BACKEND("1064", "doris.exception.no_living_backend"),
    DUPLICATE_TABLE_ALIAS("1066", "doris.exception.duplicate_table_alias"),
    INVALID_THREAD_ID("1094", "doris.exception.invalid_thread_id"),
    KILL_THREAD_NOT_OWNER("1095", "doris.exception.kill_thread_not_owner"),
    NO_TABLE_SPECIFIED("1096", "doris.exception.no_table_specified"),
    INCORRECT_DATABASE_NAME("1102", "doris.exception.incorrect_database_name"),
    INCORRECT_TABLE_NAME("1104", "doris.exception.incorrect_table_name"),
    OTHER_ERROR("1105", "doris.exception.other_error"),
    UNKNOWN_TABLE_IN_CURRENT_DATABASE("1109", "doris.exception.unknown_table_in_current_database"),
    DUPLICATE_COLUMN_IN_SUBQUERY("1110", "doris.exception.duplicate_column_in_subquery"),
    AGGREGATE_FUNCTION_ILLEGAL_USE("1111", "doris.exception.aggregate_function_illegal_use"),
    COLUMN_LIST_EMPTY_ON_CREATE("1113", "doris.exception.column_list_empty_on_create"),
    UNSUPPORTED_CHARACTER_SET("1115", "doris.exception.unsupported_character_set"),
    CLIENT_IP_NOT_AUTHORIZED("1130", "doris.exception.client_ip_not_authorized"),
    NO_PERMISSION_TO_MODIFY_PASSWORD("1132", "doris.exception.no_permission_to_modify_password"),
    REVOKE_NON_EXISTENT_PERMISSION("1141", "doris.exception.revoke_non_existent_permission"),
    UNAUTHORIZED_OPERATION("1142", "doris.exception.unauthorized_operation"),
    INCORRECT_COLUMN_NAME("1166", "doris.exception.incorrect_column_name"),
    INVALID_SYSTEM_VARIABLE_NAME("1193", "doris.exception.invalid_system_variable_name"),
    USER_CONNECTIONS_EXCEEDED("1203", "doris.exception.user_connections_exceeded"),
    CREATING_NEW_USER_NOT_ALLOWED("1211", "doris.exception.creating_new_user_not_allowed"),
    ACCESS_DENIED("1227", "doris.exception.access_denied"),
    GLOBAL_VARIABLE_CANNOT_BE_SET("1228", "doris.exception.global_variable_cannot_be_set"),
    SET_GLOBAL_REQUIRED("1229", "doris.exception.set_global_required"),
    SYSTEM_VARIABLE_NO_DEFAULT("1230", "doris.exception.system_variable_no_default"),
    INVALID_VALUE_FOR_SYSTEM_VARIABLE("1231", "doris.exception.invalid_value_for_system_variable"),
    INVALID_DATA_TYPE_FOR_SYSTEM_VARIABLE("1232", "doris.exception.invalid_data_type_for_system_variable"),
    NO_ALIAS_FOR_INLINE_VIEW("1248", "doris.exception.no_alias_for_inline_view"),
    CLIENT_AUTH_PROTOCOL_NOT_SUPPORTED("1251", "doris.exception.client_auth_protocol_not_supported"),
    INCORRECT_STORAGE_ENGINE("1286", "doris.exception.incorrect_storage_engine"),
    INCORRECT_TIME_ZONE("1298", "doris.exception.incorrect_time_zone"),
    OBJECT_MISMATCH_EXPECTED_TYPE("1347", "doris.exception.object_mismatch_expected_type"),
    FIELD_LIST_MISMATCH_IN_SELECT_AND_VIEW("1353", "doris.exception.field_list_mismatch_in_select_and_view"),
    FIELD_DOES_NOT_ALLOW_NULL("1364", "doris.exception.field_does_not_allow_null"),
    INSUFFICIENT_PASSWORD_LENGTH("1372", "doris.exception.insufficient_password_length"),
    OPERATION_FAILED("1396", "doris.exception.operation_failed"),
    NO_INSERT_PERMISSION_ON_TABLE("1471", "doris.exception.no_insert_permission_on_table"),
    PARTITION_NOT_EXISTS_NO_IF_EXISTS_CLAUSE("1507", "doris.exception.partition_not_exists_no_if_exists_clause"),
    CANNOT_DROP_ALL_PARTITIONS("1508", "doris.exception.cannot_drop_all_partitions"),
    DUPLICATE_PARTITION_NAME("1517", "doris.exception.duplicate_partition_name"),
    INCORRECT_PARTITION_NAME("1567", "doris.exception.incorrect_partition_name"),
    PARTITION_NAME_NOT_EXISTS("1735", "doris.exception.partition_name_not_exists"),
    INSERT_INTO_TABLE_WITH_EMPTY_PARTITION("1748", "doris.exception.insert_into_table_with_empty_partition"),
    PARTITION_DOES_NOT_EXIST("1749", "doris.exception.partition_does_not_exist"),
    NOT_OLAP_TABLE("5000", "doris.exception.not_olap_table"),
    INVALID_PROC_PATH("5001", "doris.exception.invalid_proc_path"),
    COLUMN_NAME_NOT_SPECIFIED_IN_COLUMN_PERMUTATION("5002", "doris.exception.column_name_not_specified_in_column_permutation"),
    KEY_COLUMN_SHOULD_PRECEDE_VALUE_COLUMN("5003", "doris.exception.key_column_should_precede_value_column"),
    AT_LEAST_ONE_KEY_COLUMN_REQUIRED("5004", "doris.exception.at_least_one_key_column_required"),
    INVALID_CLUSTER_ID("5005", "doris.exception.invalid_cluster_id"),
    INVALID_QUERY_PLAN("5006", "doris.exception.invalid_query_plan"),
    CONFLICTING_QUERY_PLAN("5007", "doris.exception.conflicting_query_plan"),
    PARTITION_CLAUSE_ONLY_FOR_PARTITIONED_TABLE("5008", "doris.exception.partition_clause_only_for_partitioned_table"),
    PARTITION_CLAUSE_INVALID_FOR_NONPARTITIONED_TABLE("5009", "doris.exception.partition_clause_invalid_for_nonpartitioned_table"),
    COLUMN_COUNT_NOT_EQUAL_TO_SELECT_LIST("5010", "doris.exception.column_count_not_equal_to_select_list"),
    UNRESOLVED_TABLE_REFERENCE("5011", "doris.exception.unresolved_table_reference"),
    INVALID_NUMERIC_VALUE_SPECIFIED("5012", "doris.exception.invalid_numeric_value_specified"),
    UNSUPPORTED_TIME_UNIT("5013", "doris.exception.unsupported_time_unit"),
    ABNORMAL_TABLE_STATUS("5014", "doris.exception.abnormal_table_status"),
    ABNORMAL_PARTITION_STATUS("5015", "doris.exception.abnormal_partition_status"),
    DATA_IMPORT_TASK_ON_PARTITION("5016", "doris.exception.data_import_task_on_partition"),
    SPECIFIED_COLUMN_NOT_KEY_COLUMN("5017", "doris.exception.specified_column_not_key_column"),
    INVALID_VALUE_FORMAT("5018", "doris.exception.invalid_value_format"),
    DATA_REPLICATION_VERSION_MISMATCH("5019", "doris.exception.data_replication_version_mismatch"),
    BE_NODE_OFFLINE("5021", "doris.exception.be_node_offline"),
    PARTITION_COUNT_NOT_ONE_IN_NONPARTITIONED_TABLE("5022", "doris.exception.partition_count_not_one_in_nonpartitioned_table"),
    NO_OPERATIONS_SPECIFIED_IN_ALTER_STATEMENT("5023", "doris.exception.no_operations_specified_in_alter_statement"),
    TASK_EXECUTION_TIMEOUT("5024", "doris.exception.task_execution_timeout"),
    DATA_INSERTION_OPERATION_FAILED("5025", "doris.exception.data_insertion_operation_failed"),
    UNSUPPORTED_DATA_TYPE_USED_IN_TABLE_CREATION_FROM_SELECT("5026", "doris.exception.unsupported_data_type_used_in_table_creation_from_select"),
    UNSET_PARAMETER_SPECIFIED("5027", "doris.exception.unset_parameter_specified"),
    SPECIFIED_CLUSTER_NOT_FOUND("5028", "doris.exception.specified_cluster_not_found"),
    NO_ACCESS_PERMISSION_TO_CLUSTER("5030", "doris.exception.no_access_permission_to_cluster"),
    NO_PARAMETER_SPECIFIED_OR_INVALID("5031", "doris.exception.no_parameter_specified_or_invalid"),
    NO_CLUSTER_INSTANCE_COUNT_SPECIFIED("5032", "doris.exception.no_cluster_instance_count_specified"),
    CLUSTER_NAME_ALREADY_EXISTS("5034", "doris.exception.cluster_name_already_exists"),
    CLUSTER_ALREADY_EXISTS("5035", "doris.exception.cluster_already_exists"),
    INSUFFICIENT_BE_NODES_IN_CLUSTER("5036", "doris.exception.insufficient_be_nodes_in_cluster"),
    ALL_DATABASES_MUST_BE_DELETED_BEFORE_CLUSTER("5037", "doris.exception.all_databases_must_be_deleted_before_cluster"),
    NO_CLUSTER_ID_SPECIFIED_FOR_BE_NODE("5037", "doris.exception.no_cluster_id_specified_for_be_node"),
    NO_CLUSTER_NAME_SPECIFIED("5038", "doris.exception.no_cluster_name_specified"),
    UNKNOWN_CLUSTER("5040", "doris.exception.unknown_cluster"),
    NO_CLUSTER_NAME("5041", "doris.exception.no_cluster_name"),
    NO_PERMISSION("5042", "doris.exception.no_permission"),
    INSTANCE_COUNT_SHOULD_BE_POSITIVE("5043", "doris.exception.instance_count_should_be_positive"),
    SOURCE_CLUSTER_NOT_EXISTS("5046", "doris.exception.source_cluster_not_exists"),
    DESTINATION_CLUSTER_NOT_EXISTS("5047", "doris.exception.destination_cluster_not_exists"),
    SOURCE_DATABASE_NOT_EXISTS("5048", "doris.exception.source_database_not_exists"),
    DESTINATION_DATABASE_NOT_EXISTS("5049", "doris.exception.destination_database_not_exists"),
    NO_CLUSTER_SELECTED("5050", "doris.exception.no_cluster_selected"),
    SOURCE_DATABASE_SHOULD_CONNECT_TO_DESTINATION("5051", "doris.exception.source_database_should_connect_to_destination"),
    NO_MIGRATION_TASK_FROM_SOURCE_TO_DESTINATION("5053", "doris.exception.no_migration_task_from_source_to_destination"),
    DATABASE_ALREADY_CONNECTED_OR_MIGRATING("5054", "doris.exception.database_already_connected_or_migrating"),
    DATA_CONNECTION_OR_MIGRATION_NOT_ALLOWED_WITHIN_SAME_CLUSTER("5055", "doris.exception.data_connection_or_migration_not_allowed_within_same_cluster"),
    CANNOT_DELETE_DATABASE_ASSOCIATED_OR_MIGRATING("5056", "doris.exception.cannot_delete_database_associated_or_migrating"),
    CANNOT_RENAME_DATABASE_ASSOCIATED_OR_MIGRATING("5056", "doris.exception.cannot_rename_database_associated_or_migrating"),
    INSUFFICIENT_BE_NODES_SPECIFIED_IN_CLUSTER("5056", "doris.exception.insufficient_be_nodes_specified_in_cluster"),
    OFFLINE_BE_NODES_IN_CLUSTER("5059", "doris.exception.offline_be_nodes_in_cluster"),
    INVALID_CLUSTER_NAME_RESERVED("5062", "doris.exception.invalid_cluster_name_reserved"),
    INCORRECT_TYPE_NAME("5063", "doris.exception.incorrect_type_name"),
    GENERIC_ERROR_PROMPT("5064", "doris.exception.generic_error_prompt"),
    COLOCATE_TABLES_DISABLED_BY_ADMIN("5063", "doris.exception.colocate_tables_disabled_by_admin"),
    COLOCATE_TABLE_NOT_EXISTS("5063", "doris.exception.colocate_table_not_exists"),
    COLOCATE_TABLE_MUST_BE_OLAP("5063", "doris.exception.colocate_table_must_be_olap"),
    COLOCATE_TABLES_MUST_HAVE_SAME_REPLICA_COUNT("5063", "doris.exception.colocate_tables_must_have_same_replica_count"),
    COLOCATE_TABLES_MUST_HAVE_SAME_BUCKET_COUNT("5063", "doris.exception.colocate_tables_must_have_same_bucket_count"),
    COLOCATE_TABLE_PARTITION_COLUMN_COUNT_MUST_MATCH("5063", "doris.exception.colocate_table_partition_column_count_must_match"),
    COLOCATE_TABLE_PARTITION_COLUMN_DATA_TYPE_MUST_MATCH("5063", "doris.exception.colocate_table_partition_column_data_type_must_match"),
    SPECIFIED_TABLE_NOT_COLOCATE("5064", "doris.exception.specified_table_not_colocate"),
    INVALID_OPERATION_SPECIFIED("5065", "doris.exception.invalid_operation_specified"),
    INVALID_TIME_UNIT_SPECIFIED("5065", "doris.exception.invalid_time_unit_specified"),
    DYNAMIC_PARTITION_START_VALUE_SHOULD_BE_NEGATIVE("5066", "doris.exception.dynamic_partition_start_value_should_be_negative"),
    DYNAMIC_PARTITION_START_VALUE_NOT_VALID_NUMBER("5066", "doris.exception.dynamic_partition_start_value_not_valid_number"),
    DYNAMIC_PARTITION_END_VALUE_SHOULD_BE_POSITIVE("5066", "doris.exception.dynamic_partition_end_value_should_be_positive"),
    DYNAMIC_PARTITION_END_VALUE_NOT_VALID_NUMBER("5066", "doris.exception.dynamic_partition_end_value_not_valid_number"),
    DYNAMIC_PARTITION_END_VALUE_EMPTY("5066", "doris.exception.dynamic_partition_end_value_empty"),
    DYNAMIC_PARTITION_BUCKET_COUNT_SHOULD_BE_POSITIVE("5067", "doris.exception.dynamic_partition_bucket_count_should_be_positive"),
    DYNAMIC_PARTITION_BUCKET_VALUE_NOT_VALID_NUMBER("5067", "doris.exception.dynamic_partition_bucket_value_not_valid_number"),
    DYNAMIC_PARTITION_BUCKET_VALUE_EMPTY("5066", "doris.exception.dynamic_partition_bucket_value_empty"),
    DYNAMIC_PARTITION_ALLOW_VALUE_NOT_VALID_BOOLEAN("5068", "doris.exception.dynamic_partition_allow_value_not_valid_boolean"),
    DYNAMIC_PARTITION_PREFIX_INVALID("5069", "doris.exception.dynamic_partition_prefix_invalid"),
    OPERATION_PROHIBITED("5070", "doris.exception.operation_prohibited"),
    DYNAMIC_PARTITION_REPLICA_COUNT_SHOULD_BE_POSITIVE("5071", "doris.exception.dynamic_partition_replica_count_should_be_positive"),
    DYNAMIC_PARTITION_REPLICA_VALUE_NOT_VALID_NUMBER("5072", "doris.exception.dynamic_partition_replica_value_not_valid_number"),
    ORIGINAL_CREATE_TABLE_STATEMENT_EMPTY("5073", "doris.exception.original_create_table_statement_empty"),
    CREATE_HISTORY_PARTITION_PARAM_INVALID("5074", "doris.exception.create_history_partition_param_invalid"),
    SPECIFIED_RETAIN_HISTORY_PARTITION_PERIOD_EMPTY("5076", "doris.exception.specified_retain_history_partition_period_empty"),
    SPECIFIED_RETAIN_HISTORY_PARTITION_PERIOD_INVALID("5077", "doris.exception.specified_retain_history_partition_period_invalid"),
    SPECIFIED_RETAIN_HISTORY_PARTITION_PERIOD_PAIR_MISMATCH("5078", "doris.exception.specified_retain_history_partition_period_pair_mismatch"),
    SPECIFIED_RETAIN_HISTORY_PARTITION_PERIOD_FIRST_GREATER_THAN_SECOND("5079", "doris.exception.specified_retain_history_partition_period_first_greater_than_second");

    private final String code;
    private final String key;

    public static String getMsgByCode(String code) {
        return Arrays.stream(values())
            .filter(em -> CharSequenceUtil.equals(code, em.getCode()))
            .findFirst()
            .map(ErrorCode::getMsg)
            .orElse(CharSequenceUtil.EMPTY);
    }
}
