/* Generated By:JavaCC: Do not edit this line. ParseDorisIndex.java */
package cn.cisdigital.datakits.framework.util.sqlparser.javacc.ext.doris;

import cn.cisdigital.datakits.framework.model.dto.database.IndexDto;
import cn.cisdigital.datakits.framework.model.enums.DataBaseTypeEnum;
import cn.cisdigital.datakits.framework.model.enums.IndexTypeStrategyFactory;
import com.google.common.collect.Lists;
import java.util.List;import java.util.Properties;


public class ParseDorisIndex implements ParseDorisIndexConstants {

/**
* 批量解析索引
*/
  final public List<IndexDto> parseIndexs() throws ParseException {
    List<IndexDto> indexList = Lists.newArrayList();
    parseIndex(indexList);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      jj_consume_token(COMMA);
      parseIndex(indexList);
    }
     {if (true) return indexList;}
    throw new Error("Missing return statement in function");
  }

  final private void parseIndex(List<IndexDto> indexList) throws ParseException {
    List<String> columnList = Lists.newArrayList();
    String indexName;
    String indexType;
    String desc = "";
    Properties properties = null;
    jj_consume_token(INDEX);
    indexName = parseIdentifier();
    parseIndexColumn(columnList);
    jj_consume_token(USING);
    indexType = parseIdentifier();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PROPERTIES:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      jj_consume_token(PROPERTIES);
      properties = parseProperties();
    }
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMENT:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_3;
      }
      jj_consume_token(COMMENT);
      desc = parseIdentifier();
    }
 IndexDto indexDto = new IndexDto();
 indexDto.setIndexComment(desc);
 indexDto.setIndexName(indexName);
 indexDto.setIndexType(IndexTypeStrategyFactory.getIndexType(DataBaseTypeEnum.DORIS, indexType));
 indexDto.setColumnNameLists(columnList);
 indexDto.setProperties(properties);
 indexList.add(indexDto);
  }

  final private String parseIdentifier() throws ParseException {
 Token value;
 String identifier;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NORMAL_NAME:
      value = jj_consume_token(NORMAL_NAME);
      break;
    case INDEX:
      value = jj_consume_token(INDEX);
      break;
    case USING:
      value = jj_consume_token(USING);
      break;
    case COMMENT:
      value = jj_consume_token(COMMENT);
      break;
    case QUOTED_IDENTIFIER:
      value = jj_consume_token(QUOTED_IDENTIFIER);
                                   value.image = subIdentifier(value.image,1,value.image.length() -1);
      break;
    case SINGLE_QUOTED_IDENTIFIER:
      value = jj_consume_token(SINGLE_QUOTED_IDENTIFIER);
                                          value.image = subIdentifier(value.image,1,value.image.length() -1);
      break;
    case BACK_QUOTED_IDENTIFIER:
      value = jj_consume_token(BACK_QUOTED_IDENTIFIER);
                                        value.image = subIdentifier(value.image,1,value.image.length() -1);
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
     {if (true) return value.image;}
    throw new Error("Missing return statement in function");
  }

  final private String subIdentifier(String identifier, int start, int end) throws ParseException {
     {if (true) return identifier.substring(start,end);}
    throw new Error("Missing return statement in function");
  }

  final private void parseIndexColumn(List<String> columnList) throws ParseException {
    jj_consume_token(LPAREN);
    addColumns(columnList);
    jj_consume_token(RPAREN);
  }

  final private void addColumns(List<String> columnList) throws ParseException {
    Token x;
    addColumn(columnList);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_4;
      }
      jj_consume_token(COMMA);
      addColumn(columnList);
    }
  }

  final private void addColumn(List<String> columnList) throws ParseException {
    String x;
    x = parseIdentifier();
     columnList.add(x);
  }

  final private Properties parseProperties() throws ParseException {
   Properties properties = new Properties();
    jj_consume_token(LPAREN);
    addProperties(properties);
    jj_consume_token(RPAREN);
   {if (true) return properties;}
    throw new Error("Missing return statement in function");
  }

  final private void addProperties(Properties properties) throws ParseException {
    addProperty(properties);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_5;
      }
      jj_consume_token(COMMA);
      addProperty(properties);
    }
  }

  final private void addProperty(Properties properties) throws ParseException {
    Token key;
    Token value;
    key = jj_consume_token(QUOTED_IDENTIFIER);
    jj_consume_token(EQ);
    value = jj_consume_token(QUOTED_IDENTIFIER);
     properties.setProperty(subIdentifier(key.image,1,key.image.length() -1),subIdentifier(value.image,1,value.image.length() -1));
  }

  public ParseDorisIndexTokenManager token_source;
  SimpleCharStream jj_input_stream;
  public Token token, jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[6];
  static private int[] jj_la1_0;
  static {
      jj_la1_0();
   }
   private static void jj_la1_0() {
      jj_la1_0 = new int[] {0x10000,0x1000,0x800,0x20fc0,0x10000,0x10000,};
   }

  public ParseDorisIndex(java.io.InputStream stream) {
     this(stream, null);
  }
  public ParseDorisIndex(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParseDorisIndexTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  public ParseDorisIndex(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParseDorisIndexTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  public ParseDorisIndex(ParseDorisIndexTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  public void ReInit(ParseDorisIndexTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.Vector jj_expentries = new java.util.Vector();
  private int[] jj_expentry;
  private int jj_kind = -1;

  public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[18];
    for (int i = 0; i < 18; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 6; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 18; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  final public void enable_tracing() {
  }

  final public void disable_tracing() {
  }

    //可以再里面定义初始化信息，字符串接收方式，异常处�?..
}
